# PostgreSQL local (Docker, puerto 45432)
spring.datasource.url=jdbc:postgresql://localhost:45432/english_trainer
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=english
spring.datasource.password=english

# SQL logging para desarrollo
spring.jpa.show-sql=true

# Google OAuth
google.client-id=665283490784-pun06n42ncj247ga3rk4b3p0i0aj25eg.apps.googleusercontent.com
