INSERT INTO achievements (id, name, description, icon, xp_reward) VALUES
('first_session', 'First Steps', 'Complete your first session', 'rocket', 50),
('sessions_10', 'Getting Started', 'Complete 10 sessions', 'fire', 100),
('sessions_25', 'Committed', 'Complete 25 sessions', 'star', 200),
('sessions_50', 'Dedicated', 'Complete 50 sessions', 'trophy', 300),
('sessions_100', 'Centurion', 'Complete 100 sessions', 'crown', 500),
('streak_3', 'Three Day Streak', 'Maintain a 3-day streak', 'flame', 50),
('streak_7', 'Week Warrior', 'Maintain a 7-day streak', 'sword', 100),
('streak_14', 'Fortnight Fighter', 'Maintain a 14-day streak', 'shield', 200),
('streak_30', 'Monthly Master', 'Maintain a 30-day streak', 'diamond', 500),
('flashcards_50', 'Card Collector', 'Study 50 flashcards', 'cards', 50),
('flashcards_200', 'Card Master', 'Study 200 flashcards', 'deck', 200),
('module_levelup', 'Level Up', 'Level up in any module', 'arrow_up', 200),
('global_b1', 'Intermediate', 'Reach B1 in all modules', 'medal_bronze', 500),
('global_b2', 'Upper Intermediate', 'Reach B2 in all modules', 'medal_silver', 750),
('global_c1', 'Advanced', 'Reach C1 in all modules', 'medal_gold', 1000),
('week_active', 'Active Week', 'Be active every day for a week', 'calendar', 100),
('xp_1000', 'XP Hunter', 'Earn 1000 XP', 'gem', 100),
('xp_5000', 'XP Master', 'Earn 5000 XP', 'crystal', 300),
('first_test', 'Test Taker', 'Complete the level test', 'clipboard', 50),
('first_review', 'Reviewer', 'Complete a spaced repetition review', 'refresh', 50),
('reviews_50', 'Review Pro', 'Complete 50 reviews', 'cycle', 200),
('perfect_score', 'Perfect Score', 'Score 100% on any unit', 'bullseye', 100),
('all_modules', 'Well Rounded', 'Complete at least one unit in all 5 modules', 'globe', 150);
