ALTER TABLE conversations ADD COLUMN IF NOT EXISTS grammar_accuracy DOUBLE PRECISION;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS vocab_count INTEGER DEFAULT 0;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS avg_confidence DOUBLE PRECISION;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS message_count INTEGER DEFAULT 0;
