-- A1 Bloques 6-10 (100 palabras)

-- Bloque 6: Compras y dinero (20 palabras)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'money', '/ˈmʌni/', 'dinero', 'noun', 'I need more money.', 'a1', 'prices', 6, 'Compras y dinero'),
(gen_random_uuid(), 'price', '/praɪs/', 'precio', 'noun', 'What is the price?', 'a1', 'prices', 6, 'Compras y dinero'),
(gen_random_uuid(), 'cheap', '/tʃiːp/', 'barato', 'adjective', 'This shirt is cheap.', 'a1', 'prices', 6, 'Compras y dinero'),
(gen_random_uuid(), 'expensive', '/ɪkˈspɛnsɪv/', 'caro', 'adjective', 'The hotel is expensive.', 'a1', 'prices', 6, 'Compras y dinero'),
(gen_random_uuid(), 'buy', '/baɪ/', 'comprar', 'verb', 'I want to buy a book.', 'a1', 'shops', 6, 'Compras y dinero'),
(gen_random_uuid(), 'sell', '/sɛl/', 'vender', 'verb', 'They sell fruit here.', 'a1', 'shops', 6, 'Compras y dinero'),
(gen_random_uuid(), 'pay', '/peɪ/', 'pagar', 'verb', 'I need to pay the bill.', 'a1', 'prices', 6, 'Compras y dinero'),
(gen_random_uuid(), 'store', '/stɔːr/', 'tienda', 'noun', 'The store closes at 9.', 'a1', 'shops', 6, 'Compras y dinero'),
(gen_random_uuid(), 'market', '/ˈmɑːrkɪt/', 'mercado', 'noun', 'We go to the market on Saturdays.', 'a1', 'shops', 6, 'Compras y dinero'),
(gen_random_uuid(), 'shirt', '/ʃɜːrt/', 'camisa', 'noun', 'I need a new shirt.', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'shoes', '/ʃuːz/', 'zapatos', 'noun', 'My shoes are old.', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'dress', '/drɛs/', 'vestido', 'noun', 'She wears a red dress.', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'bag', '/bæɡ/', 'bolsa', 'noun', 'Put it in the bag.', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'hat', '/hæt/', 'sombrero', 'noun', 'He wears a hat in summer.', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'coat', '/koʊt/', 'abrigo', 'noun', 'Wear your coat, it is cold.', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'size', '/saɪz/', 'talla', 'noun', 'What size do you need?', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'color', '/ˈkʌlər/', 'color', 'noun', 'What color do you want?', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'red', '/rɛd/', 'rojo', 'adjective', 'The car is red.', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'blue', '/bluː/', 'azul', 'adjective', 'The sky is blue.', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'black', '/blæk/', 'negro', 'adjective', 'I have black shoes.', 'a1', 'clothes', 6, 'Compras y dinero');

-- Bloque 7: Tiempo libre (20 palabras)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'music', '/ˈmjuːzɪk/', 'música', 'noun', 'I like to listen to music.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'film', '/fɪlm/', 'película', 'noun', 'We watched a good film.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'game', '/ɡeɪm/', 'juego', 'noun', 'Let us play a game.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'sport', '/spɔːrt/', 'deporte', 'noun', 'Football is a popular sport.', 'a1', 'sports', 7, 'Tiempo libre'),
(gen_random_uuid(), 'football', '/ˈfʊtbɔːl/', 'fútbol', 'noun', 'I play football on Sundays.', 'a1', 'sports', 7, 'Tiempo libre'),
(gen_random_uuid(), 'swim', '/swɪm/', 'nadar', 'verb', 'I swim in the pool.', 'a1', 'sports', 7, 'Tiempo libre'),
(gen_random_uuid(), 'play', '/pleɪ/', 'jugar', 'verb', 'Children play in the park.', 'a1', 'sports', 7, 'Tiempo libre'),
(gen_random_uuid(), 'watch', '/wɒtʃ/', 'ver', 'verb', 'I watch TV at night.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'listen', '/ˈlɪsn/', 'escuchar', 'verb', 'I listen to music every day.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'dance', '/dæns/', 'bailar', 'verb', 'She likes to dance.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'sing', '/sɪŋ/', 'cantar', 'verb', 'He can sing very well.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'draw', '/drɔː/', 'dibujar', 'verb', 'I like to draw animals.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'photo', '/ˈfoʊtoʊ/', 'foto', 'noun', 'Can I take a photo?', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'holiday', '/ˈhɒlɪdeɪ/', 'vacaciones', 'noun', 'We go on holiday in August.', 'a1', 'weekend', 7, 'Tiempo libre'),
(gen_random_uuid(), 'weekend', '/ˌwiːkˈɛnd/', 'fin de semana', 'noun', 'I rest at the weekend.', 'a1', 'weekend', 7, 'Tiempo libre'),
(gen_random_uuid(), 'party', '/ˈpɑːrti/', 'fiesta', 'noun', 'We had a birthday party.', 'a1', 'weekend', 7, 'Tiempo libre'),
(gen_random_uuid(), 'beach', '/biːtʃ/', 'playa', 'noun', 'We go to the beach in summer.', 'a1', 'weekend', 7, 'Tiempo libre'),
(gen_random_uuid(), 'fun', '/fʌn/', 'diversión', 'noun', 'Swimming is fun.', 'a1', 'weekend', 7, 'Tiempo libre'),
(gen_random_uuid(), 'free', '/friː/', 'libre', 'adjective', 'Are you free tomorrow?', 'a1', 'weekend', 7, 'Tiempo libre'),
(gen_random_uuid(), 'enjoy', '/ɪnˈdʒɔɪ/', 'disfrutar', 'verb', 'I enjoy reading books.', 'a1', 'hobbies', 7, 'Tiempo libre');

-- Bloque 8: Trabajo y escuela (20 palabras)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'teacher', '/ˈtiːtʃər/', 'profesor', 'noun', 'The teacher is very nice.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'student', '/ˈstjuːdənt/', 'estudiante', 'noun', 'I am a student.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'class', '/klæs/', 'clase', 'noun', 'English class starts at 9.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'lesson', '/ˈlɛsn/', 'lección', 'noun', 'Today we have a new lesson.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'pen', '/pɛn/', 'bolígrafo', 'noun', 'Can I borrow your pen?', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'paper', '/ˈpeɪpər/', 'papel', 'noun', 'I need some paper.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'computer', '/kəmˈpjuːtər/', 'ordenador', 'noun', 'I use the computer for work.', 'a1', 'office', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'phone', '/foʊn/', 'teléfono', 'noun', 'My phone is ringing.', 'a1', 'office', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'office', '/ˈɒfɪs/', 'oficina', 'noun', 'I work in an office.', 'a1', 'office', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'job', '/dʒɒb/', 'trabajo', 'noun', 'She has a good job.', 'a1', 'jobs', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'doctor', '/ˈdɒktər/', 'doctor', 'noun', 'I need to see a doctor.', 'a1', 'jobs', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'police', '/pəˈliːs/', 'policía', 'noun', 'Call the police!', 'a1', 'jobs', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'learn', '/lɜːrn/', 'aprender', 'verb', 'I want to learn English.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'teach', '/tiːtʃ/', 'enseñar', 'verb', 'She teaches mathematics.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'help', '/hɛlp/', 'ayudar', 'verb', 'Can you help me?', 'a1', 'office', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'start', '/stɑːrt/', 'empezar', 'verb', 'Classes start at 9 am.', 'a1', 'office', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'finish', '/ˈfɪnɪʃ/', 'terminar', 'verb', 'I finish work at 5 pm.', 'a1', 'office', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'exam', '/ɪɡˈzæm/', 'examen', 'noun', 'I have an exam tomorrow.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'question', '/ˈkwɛstʃən/', 'pregunta', 'noun', 'I have a question.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'answer', '/ˈænsər/', 'respuesta', 'noun', 'Do you know the answer?', 'a1', 'classroom', 8, 'Trabajo y escuela');

-- Bloque 9: Clima y naturaleza (20 palabras)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'sun', '/sʌn/', 'sol', 'noun', 'The sun is shining.', 'a1', 'weather', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'rain', '/reɪn/', 'lluvia', 'noun', 'I do not like rain.', 'a1', 'weather', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'snow', '/snoʊ/', 'nieve', 'noun', 'It snows in winter.', 'a1', 'weather', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'wind', '/wɪnd/', 'viento', 'noun', 'The wind is strong today.', 'a1', 'weather', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'hot', '/hɒt/', 'caliente', 'adjective', 'It is very hot in summer.', 'a1', 'weather', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'cold', '/koʊld/', 'frío', 'adjective', 'It is cold in winter.', 'a1', 'weather', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'warm', '/wɔːrm/', 'templado', 'adjective', 'The weather is warm today.', 'a1', 'weather', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'spring', '/sprɪŋ/', 'primavera', 'noun', 'Flowers grow in spring.', 'a1', 'seasons', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'summer', '/ˈsʌmər/', 'verano', 'noun', 'We swim in summer.', 'a1', 'seasons', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'autumn', '/ˈɔːtəm/', 'otoño', 'noun', 'Leaves fall in autumn.', 'a1', 'seasons', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'winter', '/ˈwɪntər/', 'invierno', 'noun', 'It is cold in winter.', 'a1', 'seasons', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'tree', '/triː/', 'árbol', 'noun', 'There is a big tree in the garden.', 'a1', 'animals', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'flower', '/ˈflaʊər/', 'flor', 'noun', 'She likes red flowers.', 'a1', 'animals', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'dog', '/dɒɡ/', 'perro', 'noun', 'I have a small dog.', 'a1', 'animals', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'cat', '/kæt/', 'gato', 'noun', 'The cat is sleeping.', 'a1', 'animals', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'bird', '/bɜːrd/', 'pájaro', 'noun', 'A bird is singing in the tree.', 'a1', 'animals', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'horse', '/hɔːrs/', 'caballo', 'noun', 'She rides a horse.', 'a1', 'animals', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'river', '/ˈrɪvər/', 'río', 'noun', 'The river is very long.', 'a1', 'animals', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'mountain', '/ˈmaʊntən/', 'montaña', 'noun', 'We climbed the mountain.', 'a1', 'animals', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'sky', '/skaɪ/', 'cielo', 'noun', 'The sky is blue today.', 'a1', 'weather', 9, 'Clima y naturaleza');

-- Bloque 10: Comunicacion (20 palabras)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'say', '/seɪ/', 'decir', 'verb', 'What did you say?', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'tell', '/tɛl/', 'contar', 'verb', 'Tell me your name.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'speak', '/spiːk/', 'hablar', 'verb', 'Do you speak English?', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'talk', '/tɔːk/', 'hablar', 'verb', 'We need to talk.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'ask', '/æsk/', 'preguntar', 'verb', 'Can I ask a question?', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'call', '/kɔːl/', 'llamar', 'verb', 'I will call you later.', 'a1', 'phone', 10, 'Comunicación'),
(gen_random_uuid(), 'send', '/sɛnd/', 'enviar', 'verb', 'Send me a message.', 'a1', 'phone', 10, 'Comunicación'),
(gen_random_uuid(), 'email', '/ˈiːmeɪl/', 'correo electrónico', 'noun', 'I will send you an email.', 'a1', 'internet', 10, 'Comunicación'),
(gen_random_uuid(), 'message', '/ˈmɛsɪdʒ/', 'mensaje', 'noun', 'I got your message.', 'a1', 'phone', 10, 'Comunicación'),
(gen_random_uuid(), 'internet', '/ˈɪntərˌnɛt/', 'internet', 'noun', 'I use the internet every day.', 'a1', 'internet', 10, 'Comunicación'),
(gen_random_uuid(), 'name', '/neɪm/', 'nombre', 'noun', 'What is your name?', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'word', '/wɜːrd/', 'palabra', 'noun', 'I learned a new word today.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'language', '/ˈlæŋɡwɪdʒ/', 'idioma', 'noun', 'English is a global language.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'letter', '/ˈlɛtər/', 'carta', 'noun', 'I wrote a letter to my friend.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'please', '/pliːz/', 'por favor', 'adverb', 'Please sit down.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'thank', '/θæŋk/', 'agradecer', 'verb', 'Thank you very much.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'sorry', '/ˈsɒri/', 'lo siento', 'adjective', 'I am sorry for the mistake.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'yes', '/jɛs/', 'sí', 'adverb', 'Yes, I understand.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'no', '/noʊ/', 'no', 'adverb', 'No, thank you.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'understand', '/ˌʌndərˈstænd/', 'entender', 'verb', 'I do not understand.', 'a1', 'social', 10, 'Comunicación');
