-- A2 Bloques 1-5 (100 palabras)

-- Bloque 1: Relaciones y sentimientos (20 palabras)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'husband', '/ˈhʌzbənd/', 'marido', 'noun', 'Her husband works in a bank.', 'a2', 'relationships', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'wife', '/waɪf/', 'esposa', 'noun', 'His wife is a teacher.', 'a2', 'relationships', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'daughter', '/ˈdɔːtər/', 'hija', 'noun', 'Their daughter is five years old.', 'a2', 'relationships', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'son', '/sʌn/', 'hijo', 'noun', 'My son likes football.', 'a2', 'relationships', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'neighbour', '/ˈneɪbər/', 'vecino', 'noun', 'My neighbour is very friendly.', 'a2', 'relationships', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'colleague', '/ˈkɒliːɡ/', 'compañero de trabajo', 'noun', 'I had lunch with a colleague.', 'a2', 'relationships', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'angry', '/ˈæŋɡri/', 'enfadado', 'adjective', 'She was angry about the mistake.', 'a2', 'feelings', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'worried', '/ˈwʌrid/', 'preocupado', 'adjective', 'I am worried about the exam.', 'a2', 'feelings', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'excited', '/ɪkˈsaɪtɪd/', 'emocionado', 'adjective', 'I am excited about the trip.', 'a2', 'feelings', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'scared', '/skɛrd/', 'asustado', 'adjective', 'The child was scared of the dark.', 'a2', 'feelings', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'surprised', '/sərˈpraɪzd/', 'sorprendido', 'adjective', 'I was surprised by the news.', 'a2', 'feelings', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'bored', '/bɔːrd/', 'aburrido', 'adjective', 'The film was boring.', 'a2', 'feelings', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'proud', '/praʊd/', 'orgulloso', 'adjective', 'I am proud of my son.', 'a2', 'feelings', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'lonely', '/ˈloʊnli/', 'solo', 'adjective', 'She feels lonely sometimes.', 'a2', 'feelings', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'love', '/lʌv/', 'amor', 'noun', 'Love is important.', 'a2', 'feelings', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'hate', '/heɪt/', 'odiar', 'verb', 'I hate waiting.', 'a2', 'feelings', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'miss', '/mɪs/', 'echar de menos', 'verb', 'I miss my family.', 'a2', 'feelings', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'marry', '/ˈmæri/', 'casarse', 'verb', 'They married last year.', 'a2', 'relationships', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'invite', '/ɪnˈvaɪt/', 'invitar', 'verb', 'I invited her to the party.', 'a2', 'relationships', 1, 'Relaciones y sentimientos'),
(gen_random_uuid(), 'agree', '/əˈɡriː/', 'estar de acuerdo', 'verb', 'I agree with you.', 'a2', 'relationships', 1, 'Relaciones y sentimientos');

-- Bloque 2: Salud y cuerpo (20 palabras)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'headache', '/ˈhɛdeɪk/', 'dolor de cabeza', 'noun', 'I have a headache.', 'a2', 'health', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'stomach', '/ˈstʌmək/', 'estómago', 'noun', 'My stomach hurts.', 'a2', 'body', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'back', '/bæk/', 'espalda', 'noun', 'My back hurts after work.', 'a2', 'body', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'tooth', '/tuːθ/', 'diente', 'noun', 'I need to see the dentist for my tooth.', 'a2', 'body', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'knee', '/niː/', 'rodilla', 'noun', 'I hurt my knee playing football.', 'a2', 'body', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'finger', '/ˈfɪŋɡər/', 'dedo', 'noun', 'I cut my finger.', 'a2', 'body', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'medicine', '/ˈmɛdɪsɪn/', 'medicina', 'noun', 'Take this medicine twice a day.', 'a2', 'health', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'ill', '/ɪl/', 'enfermo', 'adjective', 'I feel ill today.', 'a2', 'health', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'pain', '/peɪn/', 'dolor', 'noun', 'I have a pain in my leg.', 'a2', 'health', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'fever', '/ˈfiːvər/', 'fiebre', 'noun', 'The child has a fever.', 'a2', 'health', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'cough', '/kɒf/', 'tos', 'noun', 'I have a bad cough.', 'a2', 'health', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'appointment', '/əˈpɔɪntmənt/', 'cita', 'noun', 'I have a doctor appointment.', 'a2', 'health', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'exercise', '/ˈɛksərsaɪz/', 'ejercicio', 'noun', 'Exercise is good for your health.', 'a2', 'health', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'healthy', '/ˈhɛlθi/', 'saludable', 'adjective', 'Fruit is healthy.', 'a2', 'health', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'strong', '/strɒŋ/', 'fuerte', 'adjective', 'He is very strong.', 'a2', 'body', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'weak', '/wiːk/', 'débil', 'adjective', 'She feels weak after the illness.', 'a2', 'body', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'rest', '/rɛst/', 'descansar', 'verb', 'You need to rest.', 'a2', 'health', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'hurt', '/hɜːrt/', 'doler', 'verb', 'My arm hurts.', 'a2', 'health', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'breathe', '/briːð/', 'respirar', 'verb', 'Breathe slowly.', 'a2', 'body', 2, 'Salud y cuerpo'),
(gen_random_uuid(), 'weight', '/weɪt/', 'peso', 'noun', 'I want to lose weight.', 'a2', 'body', 2, 'Salud y cuerpo');

-- Bloque 3: Viajes y transporte (20 palabras)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'airport', '/ˈɛrpɔːrt/', 'aeropuerto', 'noun', 'We arrived at the airport early.', 'a2', 'travel', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'ticket', '/ˈtɪkɪt/', 'billete', 'noun', 'I bought a train ticket.', 'a2', 'travel', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'passport', '/ˈpæspɔːrt/', 'pasaporte', 'noun', 'Do not forget your passport.', 'a2', 'travel', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'luggage', '/ˈlʌɡɪdʒ/', 'equipaje', 'noun', 'My luggage is heavy.', 'a2', 'travel', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'flight', '/flaɪt/', 'vuelo', 'noun', 'The flight was delayed.', 'a2', 'travel', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'hotel', '/hoʊˈtɛl/', 'hotel', 'noun', 'We stayed at a nice hotel.', 'a2', 'travel', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'reservation', '/ˌrɛzərˈveɪʃn/', 'reserva', 'noun', 'I made a reservation online.', 'a2', 'travel', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'platform', '/ˈplætfɔːrm/', 'andén', 'noun', 'The train leaves from platform 3.', 'a2', 'transport', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'taxi', '/ˈtæksi/', 'taxi', 'noun', 'I took a taxi to the hotel.', 'a2', 'transport', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'bicycle', '/ˈbaɪsɪkl/', 'bicicleta', 'noun', 'I ride my bicycle to work.', 'a2', 'transport', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'arrive', '/əˈraɪv/', 'llegar', 'verb', 'We arrive at 10 am.', 'a2', 'travel', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'leave', '/liːv/', 'salir', 'verb', 'The bus leaves in 5 minutes.', 'a2', 'travel', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'travel', '/ˈtrævl/', 'viajar', 'verb', 'I love to travel.', 'a2', 'travel', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'visit', '/ˈvɪzɪt/', 'visitar', 'verb', 'I want to visit Paris.', 'a2', 'travel', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'return', '/rɪˈtɜːrn/', 'volver', 'verb', 'I will return next week.', 'a2', 'travel', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'abroad', '/əˈbrɔːd/', 'en el extranjero', 'adverb', 'She lives abroad.', 'a2', 'travel', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'fast', '/fæst/', 'rápido', 'adjective', 'The train is very fast.', 'a2', 'transport', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'slow', '/sloʊ/', 'lento', 'adjective', 'The bus is slow.', 'a2', 'transport', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'delay', '/dɪˈleɪ/', 'retraso', 'noun', 'There was a long delay.', 'a2', 'travel', 3, 'Viajes y transporte'),
(gen_random_uuid(), 'journey', '/ˈdʒɜːrni/', 'viaje', 'noun', 'The journey took three hours.', 'a2', 'travel', 3, 'Viajes y transporte');

-- Bloque 4: Cocina y recetas (20 palabras)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'recipe', '/ˈrɛsɪpi/', 'receta', 'noun', 'I found a new recipe online.', 'a2', 'cooking', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'ingredient', '/ɪnˈɡriːdiənt/', 'ingrediente', 'noun', 'We need three ingredients.', 'a2', 'cooking', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'bowl', '/boʊl/', 'bol', 'noun', 'Put the salad in a bowl.', 'a2', 'kitchen', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'plate', '/pleɪt/', 'plato', 'noun', 'The plate is on the table.', 'a2', 'kitchen', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'glass', '/ɡlæs/', 'vaso', 'noun', 'Can I have a glass of water?', 'a2', 'kitchen', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'knife', '/naɪf/', 'cuchillo', 'noun', 'Be careful with the knife.', 'a2', 'kitchen', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'fork', '/fɔːrk/', 'tenedor', 'noun', 'Use your fork to eat.', 'a2', 'kitchen', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'spoon', '/spuːn/', 'cuchara', 'noun', 'Stir with a spoon.', 'a2', 'kitchen', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'fry', '/fraɪ/', 'freír', 'verb', 'Fry the onions in oil.', 'a2', 'cooking', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'boil', '/bɔɪl/', 'hervir', 'verb', 'Boil the water first.', 'a2', 'cooking', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'mix', '/mɪks/', 'mezclar', 'verb', 'Mix the flour and eggs.', 'a2', 'cooking', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'cut', '/kʌt/', 'cortar', 'verb', 'Cut the tomatoes.', 'a2', 'cooking', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'taste', '/teɪst/', 'sabor', 'noun', 'This soup has a good taste.', 'a2', 'cooking', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'sweet', '/swiːt/', 'dulce', 'adjective', 'The cake is very sweet.', 'a2', 'cooking', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'sour', '/saʊər/', 'ácido', 'adjective', 'Lemons are sour.', 'a2', 'cooking', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'spicy', '/ˈspaɪsi/', 'picante', 'adjective', 'This curry is very spicy.', 'a2', 'cooking', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'fresh', '/frɛʃ/', 'fresco', 'adjective', 'I like fresh vegetables.', 'a2', 'cooking', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'frozen', '/ˈfroʊzn/', 'congelado', 'adjective', 'We bought frozen pizza.', 'a2', 'cooking', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'delicious', '/dɪˈlɪʃəs/', 'delicioso', 'adjective', 'The food was delicious.', 'a2', 'cooking', 4, 'Cocina y recetas'),
(gen_random_uuid(), 'menu', '/ˈmɛnjuː/', 'menú', 'noun', 'Can I see the menu?', 'a2', 'cooking', 4, 'Cocina y recetas');

-- Bloque 5: Descripcion y apariencia (20 palabras)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'beautiful', '/ˈbjuːtɪfl/', 'hermoso', 'adjective', 'The sunset is beautiful.', 'a2', 'appearance', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'ugly', '/ˈʌɡli/', 'feo', 'adjective', 'The building is ugly.', 'a2', 'appearance', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'thin', '/θɪn/', 'delgado', 'adjective', 'She is tall and thin.', 'a2', 'appearance', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'fat', '/fæt/', 'gordo', 'adjective', 'The cat is fat.', 'a2', 'appearance', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'short', '/ʃɔːrt/', 'bajo', 'adjective', 'He is short for his age.', 'a2', 'appearance', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'curly', '/ˈkɜːrli/', 'rizado', 'adjective', 'She has curly hair.', 'a2', 'appearance', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'straight', '/streɪt/', 'liso', 'adjective', 'He has straight hair.', 'a2', 'appearance', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'blonde', '/blɒnd/', 'rubio', 'adjective', 'She is blonde.', 'a2', 'appearance', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'dark', '/dɑːrk/', 'oscuro', 'adjective', 'He has dark eyes.', 'a2', 'appearance', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'beard', '/bɪrd/', 'barba', 'noun', 'He has a long beard.', 'a2', 'appearance', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'glasses', '/ˈɡlæsɪz/', 'gafas', 'noun', 'She wears glasses.', 'a2', 'appearance', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'look', '/lʊk/', 'parecer', 'verb', 'You look tired.', 'a2', 'appearance', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'wear', '/wɛr/', 'llevar puesto', 'verb', 'She wears a blue dress.', 'a2', 'appearance', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'kind', '/kaɪnd/', 'amable', 'adjective', 'She is a very kind person.', 'a2', 'personality', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'shy', '/ʃaɪ/', 'tímido', 'adjective', 'He is very shy.', 'a2', 'personality', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'friendly', '/ˈfrɛndli/', 'amigable', 'adjective', 'The people here are friendly.', 'a2', 'personality', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'lazy', '/ˈleɪzi/', 'perezoso', 'adjective', 'He is too lazy to study.', 'a2', 'personality', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'clever', '/ˈklɛvər/', 'listo', 'adjective', 'She is a clever student.', 'a2', 'personality', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'honest', '/ˈɒnɪst/', 'honesto', 'adjective', 'He is very honest.', 'a2', 'personality', 5, 'Descripción y apariencia'),
(gen_random_uuid(), 'polite', '/pəˈlaɪt/', 'educado', 'adjective', 'Always be polite.', 'a2', 'personality', 5, 'Descripción y apariencia');
