-- A2 Bloques 6-10 (100 palabras)

-- Bloque 6: Tecnologia y medios (20 palabras)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'screen', '/skriːn/', 'pantalla', 'noun', 'The screen is too bright.', 'a2', 'technology', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'keyboard', '/ˈkiːbɔːrd/', 'teclado', 'noun', 'I need a new keyboard.', 'a2', 'technology', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'website', '/ˈwɛbsaɪt/', 'sitio web', 'noun', 'I found it on a website.', 'a2', 'technology', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'password', '/ˈpæswɜːrd/', 'contraseña', 'noun', 'I forgot my password.', 'a2', 'technology', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'download', '/ˈdaʊnloʊd/', 'descargar', 'verb', 'I need to download the app.', 'a2', 'technology', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'search', '/sɜːrtʃ/', 'buscar', 'verb', 'Search for it on the internet.', 'a2', 'technology', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'share', '/ʃɛr/', 'compartir', 'verb', 'Share this photo with me.', 'a2', 'technology', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'click', '/klɪk/', 'hacer clic', 'verb', 'Click on the link.', 'a2', 'technology', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'newspaper', '/ˈnjuːzpeɪpər/', 'periódico', 'noun', 'I read the newspaper every morning.', 'a2', 'media', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'magazine', '/ˌmæɡəˈziːn/', 'revista', 'noun', 'She reads fashion magazines.', 'a2', 'media', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'news', '/njuːz/', 'noticias', 'noun', 'I watch the news at night.', 'a2', 'media', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'channel', '/ˈtʃænl/', 'canal', 'noun', 'Change the channel please.', 'a2', 'media', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'programme', '/ˈproʊɡræm/', 'programa', 'noun', 'This is my favourite programme.', 'a2', 'media', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'camera', '/ˈkæmərə/', 'cámara', 'noun', 'I bought a new camera.', 'a2', 'technology', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'battery', '/ˈbætəri/', 'batería', 'noun', 'My phone battery is low.', 'a2', 'technology', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'charger', '/ˈtʃɑːrdʒər/', 'cargador', 'noun', 'I forgot my charger.', 'a2', 'technology', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'online', '/ˈɒnlaɪn/', 'en línea', 'adjective', 'I bought it online.', 'a2', 'technology', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'video', '/ˈvɪdioʊ/', 'vídeo', 'noun', 'I watched a funny video.', 'a2', 'media', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'social media', '/ˈsoʊʃl ˈmiːdiə/', 'redes sociales', 'noun', 'I spend too much time on social media.', 'a2', 'technology', 6, 'Tecnología y medios'),
(gen_random_uuid(), 'app', '/æp/', 'aplicación', 'noun', 'This app is very useful.', 'a2', 'technology', 6, 'Tecnología y medios');

-- Bloque 7: Medio ambiente (20 palabras)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'environment', '/ɪnˈvaɪrənmənt/', 'medio ambiente', 'noun', 'We must protect the environment.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'pollution', '/pəˈluːʃn/', 'contaminación', 'noun', 'Air pollution is a big problem.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'recycle', '/riːˈsaɪkl/', 'reciclar', 'verb', 'We recycle plastic and paper.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'waste', '/weɪst/', 'residuo', 'noun', 'Do not waste water.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'forest', '/ˈfɒrɪst/', 'bosque', 'noun', 'The forest is very green.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'ocean', '/ˈoʊʃn/', 'océano', 'noun', 'The ocean is very deep.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'island', '/ˈaɪlənd/', 'isla', 'noun', 'We visited a beautiful island.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'lake', '/leɪk/', 'lago', 'noun', 'We swam in the lake.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'desert', '/ˈdɛzərt/', 'desierto', 'noun', 'The desert is very hot.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'field', '/fiːld/', 'campo', 'noun', 'Cows eat in the field.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'farm', '/fɑːrm/', 'granja', 'noun', 'He works on a farm.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'plant', '/plænt/', 'planta', 'noun', 'I water the plants every day.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'grow', '/ɡroʊ/', 'crecer', 'verb', 'Flowers grow in spring.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'save', '/seɪv/', 'ahorrar', 'verb', 'We need to save energy.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'protect', '/prəˈtɛkt/', 'proteger', 'verb', 'We must protect animals.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'destroy', '/dɪˈstrɔɪ/', 'destruir', 'verb', 'The fire destroyed the forest.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'natural', '/ˈnætʃərəl/', 'natural', 'adjective', 'I prefer natural food.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'dangerous', '/ˈdeɪndʒərəs/', 'peligroso', 'adjective', 'Pollution is dangerous.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'clean', '/kliːn/', 'limpio', 'adjective', 'We need clean air.', 'a2', 'nature', 7, 'Medio ambiente'),
(gen_random_uuid(), 'energy', '/ˈɛnərdʒi/', 'energía', 'noun', 'Solar energy is renewable.', 'a2', 'nature', 7, 'Medio ambiente');

-- Bloque 8: Eventos y celebraciones (20 palabras)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'birthday', '/ˈbɜːrθdeɪ/', 'cumpleaños', 'noun', 'Happy birthday!', 'a2', 'celebrations', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'wedding', '/ˈwɛdɪŋ/', 'boda', 'noun', 'The wedding was beautiful.', 'a2', 'celebrations', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'gift', '/ɡɪft/', 'regalo', 'noun', 'I bought a gift for her.', 'a2', 'celebrations', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'cake', '/keɪk/', 'tarta', 'noun', 'She made a chocolate cake.', 'a2', 'celebrations', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'candle', '/ˈkændl/', 'vela', 'noun', 'Blow out the candles.', 'a2', 'celebrations', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'celebrate', '/ˈsɛlɪbreɪt/', 'celebrar', 'verb', 'We celebrate Christmas in December.', 'a2', 'celebrations', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'congratulations', '/kənˌɡrætʃuˈleɪʃnz/', 'felicidades', 'noun', 'Congratulations on your new job!', 'a2', 'celebrations', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'ceremony', '/ˈsɛrɪmoʊni/', 'ceremonia', 'noun', 'The ceremony was in a church.', 'a2', 'celebrations', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'guest', '/ɡɛst/', 'invitado', 'noun', 'We had 50 guests at the party.', 'a2', 'celebrations', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'decoration', '/ˌdɛkəˈreɪʃn/', 'decoración', 'noun', 'The decorations are beautiful.', 'a2', 'celebrations', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'surprise', '/sərˈpraɪz/', 'sorpresa', 'noun', 'It was a big surprise.', 'a2', 'celebrations', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'concert', '/ˈkɒnsərt/', 'concierto', 'noun', 'We went to a concert.', 'a2', 'events', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'exhibition', '/ˌɛksɪˈbɪʃn/', 'exposición', 'noun', 'I visited an art exhibition.', 'a2', 'events', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'festival', '/ˈfɛstɪvl/', 'festival', 'noun', 'The music festival was amazing.', 'a2', 'events', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'ticket', '/ˈtɪkɪt/', 'entrada', 'noun', 'I bought two concert tickets.', 'a2', 'events', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'crowd', '/kraʊd/', 'multitud', 'noun', 'There was a big crowd.', 'a2', 'events', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'organize', '/ˈɔːrɡənaɪz/', 'organizar', 'verb', 'She organized the event.', 'a2', 'events', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'prepare', '/prɪˈpɛr/', 'preparar', 'verb', 'I need to prepare for the party.', 'a2', 'events', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'welcome', '/ˈwɛlkəm/', 'bienvenido', 'adjective', 'Welcome to our home!', 'a2', 'events', 8, 'Eventos y celebraciones'),
(gen_random_uuid(), 'special', '/ˈspɛʃl/', 'especial', 'adjective', 'Today is a special day.', 'a2', 'celebrations', 8, 'Eventos y celebraciones');

-- Bloque 9: Educacion y habilidades (20 palabras)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'university', '/ˌjuːnɪˈvɜːrsəti/', 'universidad', 'noun', 'She studies at university.', 'a2', 'education', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'subject', '/ˈsʌbdʒɪkt/', 'asignatura', 'noun', 'Maths is my favourite subject.', 'a2', 'education', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'degree', '/dɪˈɡriː/', 'título', 'noun', 'She has a degree in law.', 'a2', 'education', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'homework', '/ˈhoʊmwɜːrk/', 'deberes', 'noun', 'I have a lot of homework.', 'a2', 'education', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'mistake', '/mɪˈsteɪk/', 'error', 'noun', 'I made a mistake.', 'a2', 'education', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'correct', '/kəˈrɛkt/', 'correcto', 'adjective', 'Your answer is correct.', 'a2', 'education', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'wrong', '/rɒŋ/', 'incorrecto', 'adjective', 'That answer is wrong.', 'a2', 'education', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'difficult', '/ˈdɪfɪkəlt/', 'difícil', 'adjective', 'The exam was difficult.', 'a2', 'education', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'easy', '/ˈiːzi/', 'fácil', 'adjective', 'This exercise is easy.', 'a2', 'education', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'practice', '/ˈpræktɪs/', 'practicar', 'verb', 'I practice English every day.', 'a2', 'skills', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'improve', '/ɪmˈpruːv/', 'mejorar', 'verb', 'I want to improve my English.', 'a2', 'skills', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'remember', '/rɪˈmɛmbər/', 'recordar', 'verb', 'I cannot remember his name.', 'a2', 'skills', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'forget', '/fərˈɡɛt/', 'olvidar', 'verb', 'Do not forget your books.', 'a2', 'skills', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'decide', '/dɪˈsaɪd/', 'decidir', 'verb', 'I cannot decide what to eat.', 'a2', 'skills', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'choose', '/tʃuːz/', 'elegir', 'verb', 'Choose your favourite colour.', 'a2', 'skills', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'explain', '/ɪkˈspleɪn/', 'explicar', 'verb', 'Can you explain this word?', 'a2', 'skills', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'translate', '/trænzˈleɪt/', 'traducir', 'verb', 'Can you translate this for me?', 'a2', 'skills', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'pronounce', '/prəˈnaʊns/', 'pronunciar', 'verb', 'How do you pronounce this word?', 'a2', 'skills', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'skill', '/skɪl/', 'habilidad', 'noun', 'Writing is an important skill.', 'a2', 'skills', 9, 'Educación y habilidades'),
(gen_random_uuid(), 'knowledge', '/ˈnɒlɪdʒ/', 'conocimiento', 'noun', 'Knowledge is power.', 'a2', 'skills', 9, 'Educación y habilidades');

-- Bloque 10: Dinero y servicios (20 palabras)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'bank', '/bæŋk/', 'banco', 'noun', 'I need to go to the bank.', 'a2', 'finance', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'account', '/əˈkaʊnt/', 'cuenta', 'noun', 'I opened a bank account.', 'a2', 'finance', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'salary', '/ˈsæləri/', 'salario', 'noun', 'He earns a good salary.', 'a2', 'finance', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'bill', '/bɪl/', 'factura', 'noun', 'Can I have the bill please?', 'a2', 'finance', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'coin', '/kɔɪn/', 'moneda', 'noun', 'I found a coin on the floor.', 'a2', 'finance', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'cash', '/kæʃ/', 'efectivo', 'noun', 'I pay with cash.', 'a2', 'finance', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'card', '/kɑːrd/', 'tarjeta', 'noun', 'Can I pay by card?', 'a2', 'finance', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'spend', '/spɛnd/', 'gastar', 'verb', 'I spend too much money.', 'a2', 'finance', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'earn', '/ɜːrn/', 'ganar', 'verb', 'She earns a lot of money.', 'a2', 'finance', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'borrow', '/ˈbɒroʊ/', 'pedir prestado', 'verb', 'Can I borrow your pen?', 'a2', 'finance', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'lend', '/lɛnd/', 'prestar', 'verb', 'Can you lend me some money?', 'a2', 'finance', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'owe', '/oʊ/', 'deber', 'verb', 'I owe you ten euros.', 'a2', 'finance', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'receipt', '/rɪˈsiːt/', 'recibo', 'noun', 'Keep the receipt.', 'a2', 'services', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'delivery', '/dɪˈlɪvəri/', 'entrega', 'noun', 'The delivery arrives tomorrow.', 'a2', 'services', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'repair', '/rɪˈpɛr/', 'reparar', 'verb', 'I need to repair my car.', 'a2', 'services', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'customer', '/ˈkʌstəmər/', 'cliente', 'noun', 'The customer is always right.', 'a2', 'services', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'service', '/ˈsɜːrvɪs/', 'servicio', 'noun', 'The service was excellent.', 'a2', 'services', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'order', '/ˈɔːrdər/', 'pedir', 'verb', 'I ordered a pizza.', 'a2', 'services', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'complain', '/kəmˈpleɪn/', 'quejarse', 'verb', 'He complained about the food.', 'a2', 'services', 10, 'Dinero y servicios'),
(gen_random_uuid(), 'recommend', '/ˌrɛkəˈmɛnd/', 'recomendar', 'verb', 'I recommend this restaurant.', 'a2', 'services', 10, 'Dinero y servicios');
