-- Block 1: Yo y mi mundo (people, body, emotions, adjectives)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'mother', '/ˈmʌðər/', 'madre', 'noun', 'My mother cooks dinner every day.', 'a1', 'people', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'father', '/ˈfɑːðər/', 'padre', 'noun', 'My father works in an office.', 'a1', 'people', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'brother', '/ˈbrʌðər/', 'hermano', 'noun', 'I have one brother and one sister.', 'a1', 'people', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'sister', '/ˈsɪstər/', 'hermana', 'noun', 'My sister is ten years old.', 'a1', 'people', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'friend', '/frɛnd/', 'amigo', 'noun', 'She is my best friend.', 'a1', 'people', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'head', '/hɛd/', 'cabeza', 'noun', 'I have a pain in my head.', 'a1', 'body', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'hand', '/hænd/', 'mano', 'noun', 'Please wash your hands.', 'a1', 'body', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'eye', '/aɪ/', 'ojo', 'noun', 'She has blue eyes.', 'a1', 'body', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'happy', '/ˈhæpi/', 'feliz', 'adjective', 'I am very happy today.', 'a1', 'emotions', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'sad', '/sæd/', 'triste', 'adjective', 'He looks sad this morning.', 'a1', 'emotions', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'tired', '/taɪərd/', 'cansado', 'adjective', 'I am tired after school.', 'a1', 'emotions', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'angry', '/ˈæŋɡri/', 'enfadado', 'adjective', 'Don''t be angry with me.', 'a1', 'emotions', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'big', '/bɪɡ/', 'grande', 'adjective', 'This is a big house.', 'a1', 'adjectives', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'small', '/smɔːl/', 'pequeño', 'adjective', 'The cat is very small.', 'a1', 'adjectives', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'old', '/oʊld/', 'viejo', 'adjective', 'My grandfather is old.', 'a1', 'adjectives', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'young', '/jʌŋ/', 'joven', 'adjective', 'She is a young woman.', 'a1', 'adjectives', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'tall', '/tɔːl/', 'alto', 'adjective', 'He is very tall.', 'a1', 'adjectives', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'name', '/neɪm/', 'nombre', 'noun', 'My name is Carlos.', 'a1', 'people', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'boy', '/bɔɪ/', 'chico', 'noun', 'The boy is playing in the park.', 'a1', 'people', 1, 'Yo y mi mundo'),
(gen_random_uuid(), 'girl', '/ɡɜːrl/', 'chica', 'noun', 'The girl reads a book.', 'a1', 'people', 1, 'Yo y mi mundo');

-- Block 2: Mi casa (rooms, furniture, household)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'house', '/haʊs/', 'casa', 'noun', 'I live in a small house.', 'a1', 'rooms', 2, 'Mi casa'),
(gen_random_uuid(), 'room', '/ruːm/', 'habitación', 'noun', 'My room is upstairs.', 'a1', 'rooms', 2, 'Mi casa'),
(gen_random_uuid(), 'kitchen', '/ˈkɪtʃɪn/', 'cocina', 'noun', 'We eat in the kitchen.', 'a1', 'rooms', 2, 'Mi casa'),
(gen_random_uuid(), 'bathroom', '/ˈbæθruːm/', 'baño', 'noun', 'The bathroom is clean.', 'a1', 'rooms', 2, 'Mi casa'),
(gen_random_uuid(), 'bedroom', '/ˈbɛdruːm/', 'dormitorio', 'noun', 'I sleep in my bedroom.', 'a1', 'rooms', 2, 'Mi casa'),
(gen_random_uuid(), 'door', '/dɔːr/', 'puerta', 'noun', 'Please close the door.', 'a1', 'household', 2, 'Mi casa'),
(gen_random_uuid(), 'window', '/ˈwɪndoʊ/', 'ventana', 'noun', 'Open the window, please.', 'a1', 'household', 2, 'Mi casa'),
(gen_random_uuid(), 'table', '/ˈteɪbəl/', 'mesa', 'noun', 'The book is on the table.', 'a1', 'furniture', 2, 'Mi casa'),
(gen_random_uuid(), 'chair', '/tʃɛr/', 'silla', 'noun', 'Please sit on the chair.', 'a1', 'furniture', 2, 'Mi casa'),
(gen_random_uuid(), 'bed', '/bɛd/', 'cama', 'noun', 'I go to bed at ten.', 'a1', 'furniture', 2, 'Mi casa'),
(gen_random_uuid(), 'floor', '/flɔːr/', 'suelo', 'noun', 'The cat is on the floor.', 'a1', 'household', 2, 'Mi casa'),
(gen_random_uuid(), 'wall', '/wɔːl/', 'pared', 'noun', 'There is a picture on the wall.', 'a1', 'household', 2, 'Mi casa'),
(gen_random_uuid(), 'lamp', '/læmp/', 'lámpara', 'noun', 'Turn on the lamp, please.', 'a1', 'furniture', 2, 'Mi casa'),
(gen_random_uuid(), 'garden', '/ˈɡɑːrdən/', 'jardín', 'noun', 'We play in the garden.', 'a1', 'rooms', 2, 'Mi casa'),
(gen_random_uuid(), 'key', '/kiː/', 'llave', 'noun', 'I lost my key.', 'a1', 'household', 2, 'Mi casa'),
(gen_random_uuid(), 'clean', '/kliːn/', 'limpio', 'adjective', 'The house is very clean.', 'a1', 'household', 2, 'Mi casa'),
(gen_random_uuid(), 'dirty', '/ˈdɜːrti/', 'sucio', 'adjective', 'The floor is dirty.', 'a1', 'household', 2, 'Mi casa'),
(gen_random_uuid(), 'live', '/lɪv/', 'vivir', 'verb', 'I live in Madrid.', 'a1', 'household', 2, 'Mi casa'),
(gen_random_uuid(), 'open', '/ˈoʊpən/', 'abrir', 'verb', 'Open the door, please.', 'a1', 'household', 2, 'Mi casa'),
(gen_random_uuid(), 'close', '/kloʊz/', 'cerrar', 'verb', 'Close the window, it is cold.', 'a1', 'household', 2, 'Mi casa');

-- Block 3: Comida y bebida (food, drinks, meals)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'water', '/ˈwɔːtər/', 'agua', 'noun', 'Can I have some water, please?', 'a1', 'drinks', 3, 'Comida y bebida'),
(gen_random_uuid(), 'milk', '/mɪlk/', 'leche', 'noun', 'I drink milk every morning.', 'a1', 'drinks', 3, 'Comida y bebida'),
(gen_random_uuid(), 'coffee', '/ˈkɔːfi/', 'café', 'noun', 'Do you want a coffee?', 'a1', 'drinks', 3, 'Comida y bebida'),
(gen_random_uuid(), 'tea', '/tiː/', 'té', 'noun', 'I like tea with sugar.', 'a1', 'drinks', 3, 'Comida y bebida'),
(gen_random_uuid(), 'bread', '/brɛd/', 'pan', 'noun', 'I eat bread for breakfast.', 'a1', 'food', 3, 'Comida y bebida'),
(gen_random_uuid(), 'rice', '/raɪs/', 'arroz', 'noun', 'We have rice for lunch.', 'a1', 'food', 3, 'Comida y bebida'),
(gen_random_uuid(), 'chicken', '/ˈtʃɪkɪn/', 'pollo', 'noun', 'I like chicken with salad.', 'a1', 'food', 3, 'Comida y bebida'),
(gen_random_uuid(), 'fish', '/fɪʃ/', 'pescado', 'noun', 'We eat fish on Fridays.', 'a1', 'food', 3, 'Comida y bebida'),
(gen_random_uuid(), 'apple', '/ˈæpəl/', 'manzana', 'noun', 'I eat an apple every day.', 'a1', 'food', 3, 'Comida y bebida'),
(gen_random_uuid(), 'egg', '/ɛɡ/', 'huevo', 'noun', 'I have two eggs for breakfast.', 'a1', 'food', 3, 'Comida y bebida'),
(gen_random_uuid(), 'cheese', '/tʃiːz/', 'queso', 'noun', 'Do you like cheese?', 'a1', 'food', 3, 'Comida y bebida'),
(gen_random_uuid(), 'sugar', '/ˈʃʊɡər/', 'azúcar', 'noun', 'No sugar in my coffee, please.', 'a1', 'food', 3, 'Comida y bebida'),
(gen_random_uuid(), 'breakfast', '/ˈbrɛkfəst/', 'desayuno', 'noun', 'Breakfast is at eight o''clock.', 'a1', 'meals', 3, 'Comida y bebida'),
(gen_random_uuid(), 'lunch', '/lʌntʃ/', 'almuerzo', 'noun', 'We have lunch at one.', 'a1', 'meals', 3, 'Comida y bebida'),
(gen_random_uuid(), 'dinner', '/ˈdɪnər/', 'cena', 'noun', 'Dinner is ready!', 'a1', 'meals', 3, 'Comida y bebida'),
(gen_random_uuid(), 'eat', '/iːt/', 'comer', 'verb', 'I eat three meals a day.', 'a1', 'food', 3, 'Comida y bebida'),
(gen_random_uuid(), 'drink', '/drɪŋk/', 'beber', 'verb', 'I drink water every day.', 'a1', 'drinks', 3, 'Comida y bebida'),
(gen_random_uuid(), 'cook', '/kʊk/', 'cocinar', 'verb', 'My mother cooks very well.', 'a1', 'food', 3, 'Comida y bebida'),
(gen_random_uuid(), 'hungry', '/ˈhʌŋɡri/', 'hambriento', 'adjective', 'I am very hungry.', 'a1', 'food', 3, 'Comida y bebida'),
(gen_random_uuid(), 'thirsty', '/ˈθɜːrsti/', 'sediento', 'adjective', 'Are you thirsty?', 'a1', 'drinks', 3, 'Comida y bebida');

-- Block 4: Rutina diaria (time, actions, frequency)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'morning', '/ˈmɔːrnɪŋ/', 'mañana', 'noun', 'I wake up early in the morning.', 'a1', 'time', 4, 'Rutina diaria'),
(gen_random_uuid(), 'afternoon', '/ˌæftərˈnuːn/', 'tarde', 'noun', 'I study in the afternoon.', 'a1', 'time', 4, 'Rutina diaria'),
(gen_random_uuid(), 'night', '/naɪt/', 'noche', 'noun', 'Good night! See you tomorrow.', 'a1', 'time', 4, 'Rutina diaria'),
(gen_random_uuid(), 'today', '/təˈdeɪ/', 'hoy', 'adverb', 'Today is a beautiful day.', 'a1', 'time', 4, 'Rutina diaria'),
(gen_random_uuid(), 'tomorrow', '/təˈmɒroʊ/', 'mañana', 'adverb', 'I have a test tomorrow.', 'a1', 'time', 4, 'Rutina diaria'),
(gen_random_uuid(), 'yesterday', '/ˈjɛstərdeɪ/', 'ayer', 'adverb', 'Yesterday I went to the park.', 'a1', 'time', 4, 'Rutina diaria'),
(gen_random_uuid(), 'always', '/ˈɔːlweɪz/', 'siempre', 'adverb', 'I always brush my teeth.', 'a1', 'frequency', 4, 'Rutina diaria'),
(gen_random_uuid(), 'never', '/ˈnɛvər/', 'nunca', 'adverb', 'I never eat fast food.', 'a1', 'frequency', 4, 'Rutina diaria'),
(gen_random_uuid(), 'sometimes', '/ˈsʌmtaɪmz/', 'a veces', 'adverb', 'I sometimes walk to school.', 'a1', 'frequency', 4, 'Rutina diaria'),
(gen_random_uuid(), 'wake up', '/weɪk ʌp/', 'despertarse', 'verb', 'I wake up at seven.', 'a1', 'actions', 4, 'Rutina diaria'),
(gen_random_uuid(), 'sleep', '/sliːp/', 'dormir', 'verb', 'I sleep eight hours every night.', 'a1', 'actions', 4, 'Rutina diaria'),
(gen_random_uuid(), 'go', '/ɡoʊ/', 'ir', 'verb', 'I go to school by bus.', 'a1', 'actions', 4, 'Rutina diaria'),
(gen_random_uuid(), 'come', '/kʌm/', 'venir', 'verb', 'Come here, please.', 'a1', 'actions', 4, 'Rutina diaria'),
(gen_random_uuid(), 'walk', '/wɔːk/', 'caminar', 'verb', 'I walk to school every day.', 'a1', 'actions', 4, 'Rutina diaria'),
(gen_random_uuid(), 'run', '/rʌn/', 'correr', 'verb', 'I run in the park on Sundays.', 'a1', 'actions', 4, 'Rutina diaria'),
(gen_random_uuid(), 'watch', '/wɒtʃ/', 'ver', 'verb', 'I watch TV in the evening.', 'a1', 'actions', 4, 'Rutina diaria'),
(gen_random_uuid(), 'read', '/riːd/', 'leer', 'verb', 'I read before I sleep.', 'a1', 'actions', 4, 'Rutina diaria'),
(gen_random_uuid(), 'write', '/raɪt/', 'escribir', 'verb', 'I write in my notebook.', 'a1', 'actions', 4, 'Rutina diaria'),
(gen_random_uuid(), 'early', '/ˈɜːrli/', 'temprano', 'adverb', 'I get up early on Mondays.', 'a1', 'time', 4, 'Rutina diaria'),
(gen_random_uuid(), 'late', '/leɪt/', 'tarde', 'adverb', 'Don''t be late for class.', 'a1', 'time', 4, 'Rutina diaria');

-- Block 5: La ciudad (places, transport, directions)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'street', '/striːt/', 'calle', 'noun', 'I live on a quiet street.', 'a1', 'places', 5, 'La ciudad'),
(gen_random_uuid(), 'park', '/pɑːrk/', 'parque', 'noun', 'We play in the park.', 'a1', 'places', 5, 'La ciudad'),
(gen_random_uuid(), 'school', '/skuːl/', 'escuela', 'noun', 'I go to school every day.', 'a1', 'places', 5, 'La ciudad'),
(gen_random_uuid(), 'hospital', '/ˈhɒspɪtəl/', 'hospital', 'noun', 'The hospital is near my house.', 'a1', 'places', 5, 'La ciudad'),
(gen_random_uuid(), 'shop', '/ʃɒp/', 'tienda', 'noun', 'There is a shop on the corner.', 'a1', 'places', 5, 'La ciudad'),
(gen_random_uuid(), 'restaurant', '/ˈrɛstərɒnt/', 'restaurante', 'noun', 'We eat at a restaurant on Saturdays.', 'a1', 'places', 5, 'La ciudad'),
(gen_random_uuid(), 'bus', '/bʌs/', 'autobús', 'noun', 'I take the bus to work.', 'a1', 'transport', 5, 'La ciudad'),
(gen_random_uuid(), 'car', '/kɑːr/', 'coche', 'noun', 'My father has a red car.', 'a1', 'transport', 5, 'La ciudad'),
(gen_random_uuid(), 'train', '/treɪn/', 'tren', 'noun', 'The train arrives at nine.', 'a1', 'transport', 5, 'La ciudad'),
(gen_random_uuid(), 'bicycle', '/ˈbaɪsɪkəl/', 'bicicleta', 'noun', 'I ride my bicycle to school.', 'a1', 'transport', 5, 'La ciudad'),
(gen_random_uuid(), 'left', '/lɛft/', 'izquierda', 'noun', 'Turn left at the corner.', 'a1', 'directions', 5, 'La ciudad'),
(gen_random_uuid(), 'right', '/raɪt/', 'derecha', 'noun', 'The bank is on the right.', 'a1', 'directions', 5, 'La ciudad'),
(gen_random_uuid(), 'near', '/nɪr/', 'cerca', 'adverb', 'The school is near my house.', 'a1', 'directions', 5, 'La ciudad'),
(gen_random_uuid(), 'far', '/fɑːr/', 'lejos', 'adverb', 'The airport is far from here.', 'a1', 'directions', 5, 'La ciudad'),
(gen_random_uuid(), 'next to', '/nɛkst tuː/', 'al lado de', 'adverb', 'The pharmacy is next to the bank.', 'a1', 'directions', 5, 'La ciudad'),
(gen_random_uuid(), 'map', '/mæp/', 'mapa', 'noun', 'Do you have a map?', 'a1', 'places', 5, 'La ciudad'),
(gen_random_uuid(), 'station', '/ˈsteɪʃən/', 'estación', 'noun', 'The train station is downtown.', 'a1', 'transport', 5, 'La ciudad'),
(gen_random_uuid(), 'airport', '/ˈɛrpɔːrt/', 'aeropuerto', 'noun', 'We go to the airport by taxi.', 'a1', 'transport', 5, 'La ciudad'),
(gen_random_uuid(), 'turn', '/tɜːrn/', 'girar', 'verb', 'Turn right at the traffic light.', 'a1', 'directions', 5, 'La ciudad'),
(gen_random_uuid(), 'stop', '/stɒp/', 'parar', 'verb', 'Stop at the red light.', 'a1', 'transport', 5, 'La ciudad');

-- Block 6: Compras y dinero (shops, prices, clothes)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'money', '/ˈmʌni/', 'dinero', 'noun', 'I don''t have enough money.', 'a1', 'prices', 6, 'Compras y dinero'),
(gen_random_uuid(), 'price', '/praɪs/', 'precio', 'noun', 'What is the price of this shirt?', 'a1', 'prices', 6, 'Compras y dinero'),
(gen_random_uuid(), 'cheap', '/tʃiːp/', 'barato', 'adjective', 'This bag is very cheap.', 'a1', 'prices', 6, 'Compras y dinero'),
(gen_random_uuid(), 'expensive', '/ɪkˈspɛnsɪv/', 'caro', 'adjective', 'That restaurant is too expensive.', 'a1', 'prices', 6, 'Compras y dinero'),
(gen_random_uuid(), 'buy', '/baɪ/', 'comprar', 'verb', 'I want to buy a new phone.', 'a1', 'shops', 6, 'Compras y dinero'),
(gen_random_uuid(), 'pay', '/peɪ/', 'pagar', 'verb', 'Can I pay by card?', 'a1', 'shops', 6, 'Compras y dinero'),
(gen_random_uuid(), 'sell', '/sɛl/', 'vender', 'verb', 'They sell fresh fruit here.', 'a1', 'shops', 6, 'Compras y dinero'),
(gen_random_uuid(), 'shirt', '/ʃɜːrt/', 'camisa', 'noun', 'I need a new white shirt.', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'shoes', '/ʃuːz/', 'zapatos', 'noun', 'These shoes are comfortable.', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'dress', '/drɛs/', 'vestido', 'noun', 'She wears a blue dress.', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'hat', '/hæt/', 'sombrero', 'noun', 'He wears a hat in summer.', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'jacket', '/ˈdʒækɪt/', 'chaqueta', 'noun', 'Take your jacket, it is cold.', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'trousers', '/ˈtraʊzərz/', 'pantalones', 'noun', 'I wear black trousers to work.', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'bag', '/bæɡ/', 'bolsa', 'noun', 'Put the books in your bag.', 'a1', 'shops', 6, 'Compras y dinero'),
(gen_random_uuid(), 'market', '/ˈmɑːrkɪt/', 'mercado', 'noun', 'We buy vegetables at the market.', 'a1', 'shops', 6, 'Compras y dinero'),
(gen_random_uuid(), 'supermarket', '/ˈsuːpərˌmɑːrkɪt/', 'supermercado', 'noun', 'The supermarket closes at nine.', 'a1', 'shops', 6, 'Compras y dinero'),
(gen_random_uuid(), 'size', '/saɪz/', 'talla', 'noun', 'What size do you wear?', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'color', '/ˈkʌlər/', 'color', 'noun', 'What color is your car?', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'red', '/rɛd/', 'rojo', 'adjective', 'I like the red one.', 'a1', 'clothes', 6, 'Compras y dinero'),
(gen_random_uuid(), 'blue', '/bluː/', 'azul', 'adjective', 'The sky is blue today.', 'a1', 'clothes', 6, 'Compras y dinero');

-- Block 7: Tiempo libre (hobbies, sports, weekend)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'music', '/ˈmjuːzɪk/', 'música', 'noun', 'I listen to music every day.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'movie', '/ˈmuːvi/', 'película', 'noun', 'Let''s watch a movie tonight.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'game', '/ɡeɪm/', 'juego', 'noun', 'Do you want to play a game?', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'book', '/bʊk/', 'libro', 'noun', 'I am reading a good book.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'football', '/ˈfʊtbɔːl/', 'fútbol', 'noun', 'I play football on Saturdays.', 'a1', 'sports', 7, 'Tiempo libre'),
(gen_random_uuid(), 'swim', '/swɪm/', 'nadar', 'verb', 'I swim in the pool on Sundays.', 'a1', 'sports', 7, 'Tiempo libre'),
(gen_random_uuid(), 'play', '/pleɪ/', 'jugar', 'verb', 'The children play in the garden.', 'a1', 'sports', 7, 'Tiempo libre'),
(gen_random_uuid(), 'dance', '/dæns/', 'bailar', 'verb', 'She likes to dance.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'sing', '/sɪŋ/', 'cantar', 'verb', 'He sings very well.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'draw', '/drɔː/', 'dibujar', 'verb', 'I like to draw pictures.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'weekend', '/ˌwiːkˈɛnd/', 'fin de semana', 'noun', 'What do you do at the weekend?', 'a1', 'weekend', 7, 'Tiempo libre'),
(gen_random_uuid(), 'holiday', '/ˈhɒlɪdeɪ/', 'vacaciones', 'noun', 'We go on holiday in August.', 'a1', 'weekend', 7, 'Tiempo libre'),
(gen_random_uuid(), 'party', '/ˈpɑːrti/', 'fiesta', 'noun', 'There is a party on Saturday.', 'a1', 'weekend', 7, 'Tiempo libre'),
(gen_random_uuid(), 'photo', '/ˈfoʊtoʊ/', 'foto', 'noun', 'Can I take a photo?', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'like', '/laɪk/', 'gustar', 'verb', 'I like playing tennis.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'love', '/lʌv/', 'amar', 'verb', 'I love reading books.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'enjoy', '/ɪnˈdʒɔɪ/', 'disfrutar', 'verb', 'I enjoy cooking on weekends.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'interesting', '/ˈɪntrəstɪŋ/', 'interesante', 'adjective', 'This book is very interesting.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'boring', '/ˈbɔːrɪŋ/', 'aburrido', 'adjective', 'The movie was boring.', 'a1', 'hobbies', 7, 'Tiempo libre'),
(gen_random_uuid(), 'fun', '/fʌn/', 'divertido', 'adjective', 'Swimming is great fun.', 'a1', 'sports', 7, 'Tiempo libre');

-- Block 8: Trabajo y escuela (jobs, classroom, office)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'teacher', '/ˈtiːtʃər/', 'profesor', 'noun', 'My teacher is very nice.', 'a1', 'jobs', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'doctor', '/ˈdɒktər/', 'médico', 'noun', 'I want to be a doctor.', 'a1', 'jobs', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'student', '/ˈstjuːdənt/', 'estudiante', 'noun', 'I am a student at this school.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'work', '/wɜːrk/', 'trabajar', 'verb', 'I work from nine to five.', 'a1', 'office', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'study', '/ˈstʌdi/', 'estudiar', 'verb', 'I study English every day.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'learn', '/lɜːrn/', 'aprender', 'verb', 'I want to learn French too.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'teach', '/tiːtʃ/', 'enseñar', 'verb', 'She teaches mathematics.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'pen', '/pɛn/', 'bolígrafo', 'noun', 'Can I borrow your pen?', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'pencil', '/ˈpɛnsəl/', 'lápiz', 'noun', 'Write with a pencil, please.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'paper', '/ˈpeɪpər/', 'papel', 'noun', 'I need a piece of paper.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'computer', '/kəmˈpjuːtər/', 'ordenador', 'noun', 'I use my computer for work.', 'a1', 'office', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'office', '/ˈɒfɪs/', 'oficina', 'noun', 'My office is on the third floor.', 'a1', 'office', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'meeting', '/ˈmiːtɪŋ/', 'reunión', 'noun', 'I have a meeting at ten.', 'a1', 'office', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'class', '/klæs/', 'clase', 'noun', 'English class starts at nine.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'homework', '/ˈhoʊmwɜːrk/', 'deberes', 'noun', 'I do my homework after dinner.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'test', '/tɛst/', 'examen', 'noun', 'We have a test on Monday.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'question', '/ˈkwɛstʃən/', 'pregunta', 'noun', 'Can I ask a question?', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'answer', '/ˈænsər/', 'respuesta', 'noun', 'I don''t know the answer.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'difficult', '/ˈdɪfɪkəlt/', 'difícil', 'adjective', 'This exercise is difficult.', 'a1', 'classroom', 8, 'Trabajo y escuela'),
(gen_random_uuid(), 'easy', '/ˈiːzi/', 'fácil', 'adjective', 'The first question is easy.', 'a1', 'classroom', 8, 'Trabajo y escuela');

-- Block 9: Clima y naturaleza (weather, seasons, animals)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'sun', '/sʌn/', 'sol', 'noun', 'The sun is shining today.', 'a1', 'weather', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'rain', '/reɪn/', 'lluvia', 'noun', 'Take an umbrella, there is rain.', 'a1', 'weather', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'snow', '/snoʊ/', 'nieve', 'noun', 'There is snow in the mountains.', 'a1', 'weather', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'wind', '/wɪnd/', 'viento', 'noun', 'The wind is very strong today.', 'a1', 'weather', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'hot', '/hɒt/', 'caliente', 'adjective', 'It is very hot in summer.', 'a1', 'weather', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'cold', '/koʊld/', 'frío', 'adjective', 'It is cold in winter.', 'a1', 'weather', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'spring', '/sprɪŋ/', 'primavera', 'noun', 'Flowers grow in spring.', 'a1', 'seasons', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'summer', '/ˈsʌmər/', 'verano', 'noun', 'We go to the beach in summer.', 'a1', 'seasons', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'autumn', '/ˈɔːtəm/', 'otoño', 'noun', 'The leaves fall in autumn.', 'a1', 'seasons', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'winter', '/ˈwɪntər/', 'invierno', 'noun', 'I wear a coat in winter.', 'a1', 'seasons', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'dog', '/dɒɡ/', 'perro', 'noun', 'I have a small dog.', 'a1', 'animals', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'cat', '/kæt/', 'gato', 'noun', 'The cat sleeps on the sofa.', 'a1', 'animals', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'bird', '/bɜːrd/', 'pájaro', 'noun', 'I can hear a bird singing.', 'a1', 'animals', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'tree', '/triː/', 'árbol', 'noun', 'There is a big tree in the garden.', 'a1', 'nature', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'flower', '/ˈflaʊər/', 'flor', 'noun', 'She likes red flowers.', 'a1', 'nature', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'river', '/ˈrɪvər/', 'río', 'noun', 'We walk by the river.', 'a1', 'nature', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'mountain', '/ˈmaʊntən/', 'montaña', 'noun', 'We can see the mountains from here.', 'a1', 'nature', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'sea', '/siː/', 'mar', 'noun', 'I love swimming in the sea.', 'a1', 'nature', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'beautiful', '/ˈbjuːtɪfəl/', 'bonito', 'adjective', 'The garden is beautiful in spring.', 'a1', 'nature', 9, 'Clima y naturaleza'),
(gen_random_uuid(), 'sky', '/skaɪ/', 'cielo', 'noun', 'The sky is clear tonight.', 'a1', 'nature', 9, 'Clima y naturaleza');

-- Block 10: Comunicacion (phone, internet, social)
INSERT INTO vocab_entries (id, en, ipa, es, type, example, level, category, block, block_title) VALUES
(gen_random_uuid(), 'phone', '/foʊn/', 'teléfono', 'noun', 'Can I use your phone?', 'a1', 'phone', 10, 'Comunicación'),
(gen_random_uuid(), 'call', '/kɔːl/', 'llamar', 'verb', 'I call my mother every day.', 'a1', 'phone', 10, 'Comunicación'),
(gen_random_uuid(), 'message', '/ˈmɛsɪdʒ/', 'mensaje', 'noun', 'I sent you a message.', 'a1', 'phone', 10, 'Comunicación'),
(gen_random_uuid(), 'email', '/ˈiːmeɪl/', 'correo electrónico', 'noun', 'Please send me an email.', 'a1', 'internet', 10, 'Comunicación'),
(gen_random_uuid(), 'internet', '/ˈɪntərˌnɛt/', 'internet', 'noun', 'I use the internet every day.', 'a1', 'internet', 10, 'Comunicación'),
(gen_random_uuid(), 'speak', '/spiːk/', 'hablar', 'verb', 'Do you speak English?', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'talk', '/tɔːk/', 'hablar', 'verb', 'Can we talk later?', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'listen', '/ˈlɪsən/', 'escuchar', 'verb', 'Listen to the teacher, please.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'understand', '/ˌʌndərˈstænd/', 'entender', 'verb', 'I don''t understand this word.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'say', '/seɪ/', 'decir', 'verb', 'What did you say?', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'ask', '/æsk/', 'preguntar', 'verb', 'Can I ask you something?', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'tell', '/tɛl/', 'contar', 'verb', 'Tell me about your day.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'know', '/noʊ/', 'saber', 'verb', 'I don''t know his name.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'think', '/θɪŋk/', 'pensar', 'verb', 'I think it is a good idea.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'help', '/hɛlp/', 'ayudar', 'verb', 'Can you help me, please?', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'thank', '/θæŋk/', 'agradecer', 'verb', 'Thank you very much!', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'sorry', '/ˈsɒri/', 'lo siento', 'adjective', 'I am sorry, I am late.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'please', '/pliːz/', 'por favor', 'adverb', 'Please sit down.', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'welcome', '/ˈwɛlkəm/', 'bienvenido', 'adjective', 'You are welcome!', 'a1', 'social', 10, 'Comunicación'),
(gen_random_uuid(), 'goodbye', '/ɡʊdˈbaɪ/', 'adiós', 'noun', 'Goodbye, see you tomorrow!', 'a1', 'social', 10, 'Comunicación');
