-- ============================================================
-- 44 IPA Phonemes for English (General American)
-- ============================================================

-- SHORT VOWELS (7)
INSERT INTO phonemes (id, symbol, name, category, subcategory, example_words, description, mouth_position, tips, difficulty_order) VALUES
(gen_random_uuid(), '/i/', 'near-close near-front unrounded', 'vowel', 'short_vowel',
 '["sit","fish","bit"]',
 'Short i as in "sit". Not as tense as the long ee.',
 'Lips slightly spread, tongue high and forward but relaxed.',
 'Think of a quick, relaxed "ee" sound. Don''t smile too wide.',
 1),
(gen_random_uuid(), '/e/', 'open-mid front unrounded', 'vowel', 'short_vowel',
 '["bed","red","said"]',
 'Short e as in "bed".',
 'Mouth slightly open, tongue mid-height and forward.',
 'Like the Spanish "e" but slightly more open.',
 2),
(gen_random_uuid(), '/ae/', 'near-open front unrounded', 'vowel', 'short_vowel',
 '["cat","hat","bad"]',
 'Short a as in "cat". This sound does not exist in Spanish.',
 'Mouth wide open, tongue low and forward.',
 'Open your mouth wider than for "e". Spread lips slightly.',
 3),
(gen_random_uuid(), '/ah/', 'open back unrounded', 'vowel', 'short_vowel',
 '["hot","stop","box"]',
 'Short o as in "hot" (American English).',
 'Mouth wide open, tongue low and back.',
 'Like saying "ah" at the doctor.',
 4),
(gen_random_uuid(), '/uh/', 'open-mid back rounded', 'vowel', 'short_vowel',
 '["cut","bus","love"]',
 'Short u as in "cup". A central relaxed vowel.',
 'Mouth slightly open, tongue mid and central, lips neutral.',
 'A quick, relaxed grunt. Very common in unstressed syllables.',
 5),
(gen_random_uuid(), '/oo/', 'near-close near-back rounded', 'vowel', 'short_vowel',
 '["book","put","good"]',
 'Short oo as in "book".',
 'Lips slightly rounded, tongue high and back but relaxed.',
 'A short, relaxed version of "oo". Don''t push lips forward too much.',
 6),
(gen_random_uuid(), '/schwa/', 'mid central', 'vowel', 'short_vowel',
 '["about","banana","sofa"]',
 'The schwa - the most common English sound. Found in unstressed syllables.',
 'Mouth relaxed and barely open, tongue central.',
 'The laziest vowel. Completely relax your mouth and make a tiny "uh".',
 7);

-- LONG VOWELS (5)
INSERT INTO phonemes (id, symbol, name, category, subcategory, example_words, description, mouth_position, tips, difficulty_order) VALUES
(gen_random_uuid(), '/ee/', 'close front unrounded', 'vowel', 'long_vowel',
 '["see","feet","beach"]',
 'Long ee as in "see". Tense and prolonged.',
 'Lips spread wide, tongue high and forward, muscles tense.',
 'Smile wide and hold the sound. Longer than short i.',
 8),
(gen_random_uuid(), '/aa/', 'open front unrounded long', 'vowel', 'long_vowel',
 '["father","car","heart"]',
 'Long ah as in "father".',
 'Mouth wide open, tongue low.',
 'A long, open "ahhh" sound.',
 9),
(gen_random_uuid(), '/aw/', 'open-mid back rounded', 'vowel', 'long_vowel',
 '["law","call","thought"]',
 'Long aw as in "law".',
 'Lips rounded, mouth fairly open, tongue low and back.',
 'Round your lips and say a low "aw".',
 10),
(gen_random_uuid(), '/ooh/', 'close back rounded', 'vowel', 'long_vowel',
 '["food","moon","blue"]',
 'Long oo as in "food".',
 'Lips tightly rounded and pushed forward, tongue high and back.',
 'Push your lips forward like blowing a kiss.',
 11),
(gen_random_uuid(), '/ur/', 'open-mid central rounded', 'vowel', 'long_vowel',
 '["bird","turn","nurse"]',
 'R-colored vowel as in "bird".',
 'Lips slightly rounded, tongue mid and central with r-coloring.',
 'Curl your tongue slightly back while making an "ur" sound.',
 12);

-- DIPHTHONGS (8)
INSERT INTO phonemes (id, symbol, name, category, subcategory, example_words, description, mouth_position, tips, difficulty_order) VALUES
(gen_random_uuid(), '/ay/', 'diphthong ay', 'vowel', 'diphthong',
 '["say","day","make"]',
 'Diphthong as in "say" - glides from eh to ee.',
 'Start with mouth open (eh), glide to spread lips (ee).',
 'Two sounds in one: "eh" + "ee". Let your jaw rise.',
 13),
(gen_random_uuid(), '/eye/', 'diphthong eye', 'vowel', 'diphthong',
 '["my","time","fly"]',
 'Diphthong as in "my" - glides from ah to ee.',
 'Start with mouth wide open (ah), glide to spread lips (ee).',
 'Open wide then close: "ah" + "ee".',
 14),
(gen_random_uuid(), '/oy/', 'diphthong oy', 'vowel', 'diphthong',
 '["boy","coin","toy"]',
 'Diphthong as in "boy" - glides from aw to ee.',
 'Start with rounded lips (aw), glide to spread (ee).',
 'Round lips then spread: "aw" + "ee".',
 15),
(gen_random_uuid(), '/ow/', 'diphthong ow', 'vowel', 'diphthong',
 '["go","home","boat"]',
 'Diphthong as in "go" - glides from oh to oo.',
 'Start with lips slightly rounded (oh), push forward to tight round (oo).',
 'Start open and round more: "oh" + "oo".',
 16),
(gen_random_uuid(), '/aw_d/', 'diphthong ow (out)', 'vowel', 'diphthong',
 '["out","now","house"]',
 'Diphthong as in "out" - glides from ah to oo.',
 'Start with mouth wide open (ah), glide to rounded lips (oo).',
 'Wide open then round: "ah" + "oo".',
 17),
(gen_random_uuid(), '/ear/', 'diphthong ear', 'vowel', 'diphthong',
 '["ear","here","beer"]',
 'Diphthong as in "ear" - glides from ee to schwa.',
 'Start with spread lips (ee), relax to central (schwa).',
 'Say "ee" then relax: "ee" + "uh".',
 18),
(gen_random_uuid(), '/air/', 'diphthong air', 'vowel', 'diphthong',
 '["air","care","bear"]',
 'Diphthong as in "air" - glides from eh to schwa.',
 'Start with mouth open (eh), relax to central (schwa).',
 'Say "eh" then relax: "eh" + "uh".',
 19),
(gen_random_uuid(), '/ure/', 'diphthong ure', 'vowel', 'diphthong',
 '["tour","pure","cure"]',
 'Diphthong as in "tour" - glides from oo to schwa.',
 'Start with rounded lips (oo), relax to central (schwa).',
 'Say "oo" then relax: "oo" + "uh".',
 20);

-- PLOSIVE CONSONANTS (6)
INSERT INTO phonemes (id, symbol, name, category, subcategory, example_words, description, mouth_position, tips, difficulty_order) VALUES
(gen_random_uuid(), '/p/', 'voiceless bilabial plosive', 'consonant', 'plosive',
 '["pen","happy","stop"]',
 'P as in "pen". Voiceless - no vocal cord vibration.',
 'Both lips pressed together, then released with a burst of air.',
 'Hold your hand in front of your mouth - you should feel a puff of air.',
 21),
(gen_random_uuid(), '/b/', 'voiced bilabial plosive', 'consonant', 'plosive',
 '["boy","baby","job"]',
 'B as in "boy". Voiced version of /p/.',
 'Both lips pressed together, then released. Vocal cords vibrate.',
 'Like /p/ but with voice. Touch your throat to feel vibration.',
 22),
(gen_random_uuid(), '/t/', 'voiceless alveolar plosive', 'consonant', 'plosive',
 '["ten","water","hat"]',
 'T as in "ten". Tongue tip touches the ridge behind upper teeth.',
 'Tongue tip on alveolar ridge, released with burst.',
 'Touch the bumpy ridge behind your top teeth with your tongue tip.',
 23),
(gen_random_uuid(), '/d/', 'voiced alveolar plosive', 'consonant', 'plosive',
 '["dog","ladder","bed"]',
 'D as in "dog". Voiced version of /t/.',
 'Same position as /t/ but with voice.',
 'Like /t/ but vibrate your vocal cords.',
 24),
(gen_random_uuid(), '/k/', 'voiceless velar plosive', 'consonant', 'plosive',
 '["cat","back","school"]',
 'K as in "cat". Back of tongue touches soft palate.',
 'Back of tongue raised to soft palate (velum), released with burst.',
 'The back of your tongue should touch the roof far back.',
 25),
(gen_random_uuid(), '/g/', 'voiced velar plosive', 'consonant', 'plosive',
 '["go","bigger","dog"]',
 'G as in "go". Voiced version of /k/.',
 'Same position as /k/ but with voice.',
 'Like /k/ but with vibration in the throat.',
 26);

-- FRICATIVES (9)
INSERT INTO phonemes (id, symbol, name, category, subcategory, example_words, description, mouth_position, tips, difficulty_order) VALUES
(gen_random_uuid(), '/f/', 'voiceless labiodental fricative', 'consonant', 'fricative',
 '["fish","coffee","leaf"]',
 'F as in "fish". Air flows between upper teeth and lower lip.',
 'Upper teeth gently touch lower lip. Air squeezed through.',
 'Gently bite your lower lip and blow.',
 27),
(gen_random_uuid(), '/v/', 'voiced labiodental fricative', 'consonant', 'fricative',
 '["van","love","movie"]',
 'V as in "van". Voiced version of /f/. Critical for Spanish speakers who often use /b/.',
 'Same position as /f/ but with voice.',
 'Upper teeth on lower lip + voice. NOT the same as /b/!',
 28),
(gen_random_uuid(), '/th_v/', 'voiceless dental fricative', 'consonant', 'fricative',
 '["think","bath","three"]',
 'Voiceless TH as in "think". Does not exist in most Spanish dialects.',
 'Tongue tip between or just behind upper teeth. Air flows over tongue.',
 'Stick your tongue between your teeth and blow gently.',
 29),
(gen_random_uuid(), '/th_d/', 'voiced dental fricative', 'consonant', 'fricative',
 '["this","mother","breathe"]',
 'Voiced TH as in "this". Like Spanish "d" between vowels but with tongue between teeth.',
 'Same as voiceless TH but with voice.',
 'Tongue between teeth + vibrate vocal cords.',
 30),
(gen_random_uuid(), '/s/', 'voiceless alveolar fricative', 'consonant', 'fricative',
 '["sun","city","bus"]',
 'S as in "sun". Tongue close to alveolar ridge.',
 'Tongue tip near alveolar ridge, sides of tongue touch upper molars.',
 'Hissing sound. Keep tongue close to the ridge.',
 31),
(gen_random_uuid(), '/z/', 'voiced alveolar fricative', 'consonant', 'fricative',
 '["zoo","buzz","easy"]',
 'Z as in "zoo". Voiced version of /s/.',
 'Same position as /s/ but with voice.',
 'Like /s/ but vibrating: a buzzing bee sound.',
 32),
(gen_random_uuid(), '/sh/', 'voiceless postalveolar fricative', 'consonant', 'fricative',
 '["she","fish","nation"]',
 'SH as in "she". Broader friction than /s/.',
 'Tongue pulled back from /s/ position. Lips slightly rounded.',
 'Like saying "shh" to quiet someone. Round your lips slightly.',
 33),
(gen_random_uuid(), '/zh/', 'voiced postalveolar fricative', 'consonant', 'fricative',
 '["measure","vision","beige"]',
 'ZH as in "measure". Voiced version of /sh/.',
 'Same position as /sh/ but with voice.',
 'Like /sh/ but with voice. Rare in English spelling.',
 34),
(gen_random_uuid(), '/h/', 'voiceless glottal fricative', 'consonant', 'fricative',
 '["hat","hello","who"]',
 'H as in "hat". A breath of air.',
 'Mouth open, air flows from glottis. No tongue/lip obstruction.',
 'Just a gentle breath out. Spanish speakers: don''t confuse with "j".',
 35);

-- AFFRICATES (2)
INSERT INTO phonemes (id, symbol, name, category, subcategory, example_words, description, mouth_position, tips, difficulty_order) VALUES
(gen_random_uuid(), '/ch/', 'voiceless postalveolar affricate', 'consonant', 'affricate',
 '["church","watch","nature"]',
 'CH as in "church". A /t/ immediately followed by /sh/.',
 'Tongue tip starts on alveolar ridge then releases into /sh/ position.',
 'Think of it as /t/ + /sh/ merged together.',
 36),
(gen_random_uuid(), '/j/', 'voiced postalveolar affricate', 'consonant', 'affricate',
 '["judge","age","bridge"]',
 'J as in "judge". Voiced version of /ch/.',
 'Same as /ch/ but with voice.',
 'Like /d/ + /zh/ merged together.',
 37);

-- NASALS (3)
INSERT INTO phonemes (id, symbol, name, category, subcategory, example_words, description, mouth_position, tips, difficulty_order) VALUES
(gen_random_uuid(), '/m/', 'bilabial nasal', 'consonant', 'nasal',
 '["man","summer","home"]',
 'M as in "man". Air flows through the nose.',
 'Both lips closed. Soft palate lowered so air goes through nose.',
 'Hum with your lips closed. Same as Spanish "m".',
 38),
(gen_random_uuid(), '/n/', 'alveolar nasal', 'consonant', 'nasal',
 '["no","dinner","sun"]',
 'N as in "no". Tongue on alveolar ridge, air through nose.',
 'Tongue tip on alveolar ridge. Soft palate lowered.',
 'Like Spanish "n" before vowels.',
 39),
(gen_random_uuid(), '/ng/', 'velar nasal', 'consonant', 'nasal',
 '["sing","ring","think"]',
 'NG as in "sing". Back of tongue on soft palate.',
 'Back of tongue against soft palate. Air through nose.',
 'Never followed by a /g/ sound in "sing". Don''t say "sing-g".',
 40);

-- APPROXIMANTS (3)
INSERT INTO phonemes (id, symbol, name, category, subcategory, example_words, description, mouth_position, tips, difficulty_order) VALUES
(gen_random_uuid(), '/r/', 'alveolar approximant', 'consonant', 'approximant',
 '["red","sorry","car"]',
 'R as in "red". Very different from Spanish rolled/tapped r.',
 'Tongue tip curled back slightly, not touching anything. Lips slightly rounded.',
 'Curl tongue back WITHOUT touching the roof. Hardest sound for Spanish speakers.',
 41),
(gen_random_uuid(), '/w/', 'labial-velar approximant', 'consonant', 'approximant',
 '["we","away","quick"]',
 'W as in "we". Lips rounded, tongue raised at back.',
 'Lips tightly rounded and pushed forward. Back of tongue raised.',
 'Start with very rounded lips, then open to the next vowel.',
 42),
(gen_random_uuid(), '/y/', 'palatal approximant', 'consonant', 'approximant',
 '["yes","you","yellow"]',
 'Y as in "yes". Tongue raised toward hard palate.',
 'Tongue body raised toward hard palate. Similar to Spanish "y".',
 'Like a very quick "ee" before the vowel.',
 43);

-- LATERAL (1)
INSERT INTO phonemes (id, symbol, name, category, subcategory, example_words, description, mouth_position, tips, difficulty_order) VALUES
(gen_random_uuid(), '/l/', 'alveolar lateral approximant', 'consonant', 'lateral',
 '["like","hello","ball"]',
 'L as in "like". Tongue tip on ridge, air flows around sides.',
 'Tongue tip on alveolar ridge. Air flows around sides of tongue.',
 'English has "light L" (beginning) and "dark L" (end). "Ball" has dark L.',
 44);
