#!/usr/bin/env python3
"""
Post-process a PPTX file generated by build_presentation.js:

1. Fix autoFit: Convert spAutoFit (resize shape) → normAutofit (shrink text)
   pptxgenjs only supports spAutoFit, but normAutofit is what we need to
   prevent text overflow in fixed-layout slides.

2. Inject Appear animations for terminal lines based on anim_meta.json.

Usage:
    python inject_animations.py --input deck.pptx --meta anim_meta.json --output deck-animated.pptx

    # Or with defaults (input=output.pptx, meta=anim_meta.json, output=output-animated.pptx)
    python inject_animations.py
"""

import argparse
import json
import xml.etree.ElementTree as ET
from pptx import Presentation
from pptx.oxml.ns import qn
from lxml import etree

P_NS = "http://schemas.openxmlformats.org/presentationml/2006/main"
A_NS = "http://schemas.openxmlformats.org/drawingml/2006/main"


def fix_autofit(prs):
    """
    Convert spAutoFit → normAutofit in all text shapes.

    pptxgenjs generates <a:spAutoFit/> (shape resizes to fit text) when
    autoFit: true is set. For presentations with fixed layouts, we need
    <a:normAutofit/> (text shrinks to fit shape) instead.

    Returns the number of shapes converted.
    """
    count = 0
    for slide in prs.slides:
        for sp in slide._element.iter(qn("p:sp")):
            body_pr = sp.find(f'.//{qn("a:bodyPr")}')
            if body_pr is None:
                continue
            sp_auto = body_pr.find(qn("a:spAutoFit"))
            if sp_auto is not None:
                body_pr.remove(sp_auto)
                norm_auto = etree.SubElement(body_pr, qn("a:normAutofit"))
                count += 1
    return count


def make_appear_timing(shape_ids_delays):
    """
    Build a <p:timing> element with sequential Appear animations.

    All animations fire on a single click, with cumulative delays creating
    a line-by-line typing effect.

    Args:
        shape_ids_delays: list of (spid, delay_ms, is_first_in_group)
    Returns:
        XML string for the <p:timing> element
    """
    tid = [1]

    def next_id():
        tid[0] += 1
        return str(tid[0])

    # Group lines: first line in a terminal = new click trigger
    click_groups = []
    current_group = []
    for spid, delay, is_first in shape_ids_delays:
        if is_first and current_group:
            click_groups.append(current_group)
            current_group = []
        current_group.append((spid, delay))
    if current_group:
        click_groups.append(current_group)

    # Build animation nodes with cumulative delays
    inner_pars = []
    cumulative_delay = 0

    for group in click_groups:
        for i, (spid, delay) in enumerate(group):
            cumulative_delay += delay
            node_type = "clickEffect" if cumulative_delay == 0 else "afterEffect"
            anim_id = next_id()
            set_id = next_id()

            par_xml = f'''<p:par xmlns:p="{P_NS}">
  <p:cTn id="{anim_id}" presetID="1" presetClass="entr" presetSubtype="0" fill="hold" nodeType="{node_type}">
    <p:stCondLst>
      <p:cond delay="{cumulative_delay if cumulative_delay > 0 else 0}"/>
    </p:stCondLst>
    <p:childTnLst>
      <p:set>
        <p:cBhvr>
          <p:cTn id="{set_id}" dur="1" fill="hold">
            <p:stCondLst>
              <p:cond delay="0"/>
            </p:stCondLst>
          </p:cTn>
          <p:tgtEl>
            <p:spTgt spid="{spid}"/>
          </p:tgtEl>
          <p:attrNameLst>
            <p:attrName>style.visibility</p:attrName>
          </p:attrNameLst>
        </p:cBhvr>
        <p:to>
          <p:strVal val="visible"/>
        </p:to>
      </p:set>
    </p:childTnLst>
  </p:cTn>
</p:par>'''
            inner_pars.append(par_xml)

    # Wrap in timing structure
    main_id = next_id()
    click_par_id = next_id()
    click_inner_id = next_id()
    inner_xml = "\n".join(inner_pars)

    timing_xml = f'''<p:timing xmlns:p="{P_NS}">
  <p:tnLst>
    <p:par>
      <p:cTn id="1" dur="indefinite" restart="never" nodeType="tmRoot">
        <p:childTnLst>
          <p:seq concurrent="1" nextAc="seek">
            <p:cTn id="{main_id}" dur="indefinite" nodeType="mainSeq">
              <p:childTnLst>
                <p:par>
                  <p:cTn id="{click_par_id}" fill="hold">
                    <p:stCondLst>
                      <p:cond delay="0"/>
                    </p:stCondLst>
                    <p:childTnLst>
                      <p:par>
                        <p:cTn id="{click_inner_id}" fill="hold">
                          <p:stCondLst>
                            <p:cond delay="0"/>
                          </p:stCondLst>
                          <p:childTnLst>
                            {inner_xml}
                          </p:childTnLst>
                        </p:cTn>
                      </p:par>
                    </p:childTnLst>
                  </p:cTn>
                </p:par>
              </p:childTnLst>
            </p:cTn>
            <p:prevCondLst>
              <p:cond evt="onPrev" delay="0">
                <p:tgtEl>
                  <p:sldTgt/>
                </p:tgtEl>
              </p:cond>
            </p:prevCondLst>
            <p:nextCondLst>
              <p:cond evt="onClick" delay="0">
                <p:tgtEl>
                  <p:sldTgt/>
                </p:tgtEl>
              </p:cond>
            </p:nextCondLst>
          </p:seq>
        </p:childTnLst>
      </p:cTn>
    </p:par>
  </p:tnLst>
</p:timing>'''

    return timing_xml


def inject(pptx_in, meta_path, pptx_out):
    """Post-process PPTX: fix autoFit and inject animations."""
    with open(meta_path) as f:
        anim_meta = json.load(f)

    prs = Presentation(pptx_in)

    # Step 1: Fix autoFit (spAutoFit → normAutofit)
    autofit_count = fix_autofit(prs)
    if autofit_count:
        print(f"  Fixed autoFit on {autofit_count} text shapes (spAutoFit → normAutofit)")

    # Step 2: Inject terminal animations
    total_anims = 0

    for slide_idx_str, line_infos in anim_meta.items():
        slide_idx = int(slide_idx_str) - 1  # 0-based

        if slide_idx >= len(prs.slides):
            print(f"⚠ Slide index {slide_idx} out of range, skipping")
            continue

        slide = prs.slides[slide_idx]
        slide_element = slide._element

        # Build name → shape_id mapping
        name_to_spid = {}
        for sp in slide_element.iter(qn("p:sp")):
            cNvPr = sp.find(f'.//{qn("p:cNvPr")}')
            if cNvPr is not None:
                name = cNvPr.get("name", "")
                spid = cNvPr.get("id", "")
                if name.startswith("termline_"):
                    name_to_spid[name] = spid

        # Match metadata to shapes
        shape_ids_delays = []
        for info in line_infos:
            name = info["name"]
            if name in name_to_spid:
                shape_ids_delays.append((
                    name_to_spid[name],
                    info["delay"],
                    info["isFirst"]
                ))

        if not shape_ids_delays:
            continue

        # Generate and inject timing XML
        timing_xml = make_appear_timing(shape_ids_delays)

        # Remove existing timing
        existing = slide_element.find(qn("p:timing"))
        if existing is not None:
            slide_element.remove(existing)

        # Inject new timing
        timing_lxml = etree.fromstring(ET.tostring(ET.fromstring(timing_xml)))
        slide_element.append(timing_lxml)

        total_anims += len(shape_ids_delays)
        print(f"  Slide {slide_idx + 1}: {len(shape_ids_delays)} animations")

    prs.save(pptx_out)
    print(f"\n✓ Saved {pptx_out} ({total_anims} total animations)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Inject Appear animations for terminal lines into PPTX"
    )
    parser.add_argument("--input", "-i", default="output.pptx",
                        help="Input PPTX file (default: output.pptx)")
    parser.add_argument("--meta", "-m", default="anim_meta.json",
                        help="Animation metadata JSON (default: anim_meta.json)")
    parser.add_argument("--output", "-o", default=None,
                        help="Output PPTX file (default: <input>-animated.pptx)")
    args = parser.parse_args()

    if args.output is None:
        base = args.input.rsplit(".", 1)[0]
        args.output = f"{base}-animated.pptx"

    print(f"Injecting animations: {args.input} → {args.output}")
    inject(args.input, args.meta, args.output)
